/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "main.h"
#define SYSTICK_RELOAD_VALUE (SystemCoreClock) / 1000 - 1
void delay(uint32_t time);

int main(void)
{
	SystemCoreClockUpdate();

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

	GPIOD->MODER |= GPIO_MODER_MODE12_0 |
					GPIO_MODER_MODE13_0 |
					GPIO_MODER_MODE14_0 |
					GPIO_MODER_MODE15_0; // set GPIO to output for LEDs

	RCC->CR |= RCC_CR_HSEON;
	while(!(RCC->CR & RCC_CR_HSERDY)){}

	RCC->CFGR |= RCC_CFGR_SW_HSE;



	SystemCoreClockUpdate();
    /* Loop forever */
	while(1){
		GPIOD->ODR ^= 	GPIO_ODR_OD12 |
						GPIO_ODR_OD13 |
						GPIO_ODR_OD14 |
						GPIO_ODR_OD15;
		delay(1000);
	}
}


void delay(uint32_t timeMS){
	for(uint32_t i = 0; i < timeMS * 1000; i++){}
}
